### PR TITLE
feat(macros): implement ClientCliArgs field-level codegen (C2)

### PR DESCRIPTION
**Pull request by lzjqsdd**
## Problem

C1 landed in #862. We need real field-level code generation before annotating
`ClientConf` in `curvine-common`.

## Design

- Generate `{Type}CliOverrides` per input struct (e.g. `ClientConfCliOverrides`).
- Use `clap::Args` (not `Parser`) for flatten into future fuse CLI surfaces.
- Container-level `#[client_cli(prefix = "client", strip_suffix = "_str")]`; field-level `skip` / `long`.
- `#[serde(skip)]` auto-skip; `apply_to` handles `Option<T>` and scalar fields.
- `apply_to` uses `::orpc::CommonResult<()>`; struct-only derive with clear errors.

## Key Changes

- Add `curvine-common/macros/src/client_cli.rs` with full derive implementation.
- Add integration tests for `apply_to` and clap flag parsing (incl. `f64`).

## Review follow-ups (szbr9486)

- Dropped `Eq`/`PartialEq`; switched to `clap::Args`.
- Removed hardcoded `master_addrs` skip; conventions live in container attributes.
- Added `try_parse_from` parsing test.

## Base

Rebased onto latest `main`, including merged #862.

## Test Plan

- [x] `cargo test -p curvine-common-macros`
- [x] `cargo fmt --check -p curvine-common-macros`

Refs #865

### CODE REVIEW

**Comment by lzjqsdd** [comment]
Rebased onto latest `main` (includes merged #862). Branch now contains **2 commits** (C2 only).

**Comment by lzjqsdd** [comment]
Addressed all Copilot review comments in 6f11923. Also rebased onto latest `main` (951ff59) and fixed `cargo fmt --check` failures.

File: curvine-common/macros/src/client_cli.rs [hunk 1]
```diff
@@ -0,0 +1,275 @@
...
+                    target.#ident = v;
+                }
+            }
+        } else {
+            quote! {
+                if let Some(v) = &self.#ident {
+                    target.#ident = v.clone();
+                }
+            }
+        };
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs]: Fixed in 6f11923: `apply_to` now detects `Option<T>` target fields and assigns `Some(v)` / `Some(v.clone())` instead of assigning `T` directly.

File: curvine-common/macros/src/client_cli.rs [hunk 2]
```diff
@@ -0,0 +1,275 @@
...
+                        if let Lit::Str(s) = expr.lit {
+                            return Some(s.value());
+                        }
+                    }
+                }
+            }
+        }
+    }
+    None
+}
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs:280]: Fixed in 6f11923: `serde_alias` now uses `parse_nested_meta`, so combined attributes like `#[serde(alias = "hugepage", default)]` are handled correctly.

File: curvine-common/macros/src/client_cli.rs [hunk 3]
```diff
@@ -0,0 +1,275 @@
...
+fn validate_cli_field_type(field: &Field) -> syn::Result<()> {
+    let inner = unwrap_option_type(&field.ty).unwrap_or(&field.ty);
+    if is_supported_cli_type(inner) {
+        Ok(())
+    } else {
+        Err(syn::Error::new_spanned(
+            &field.ty,
+            "ClientCliArgs supports String, bool, and integer types only",
+        ))
+    }
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs:291]: Fixed in 6f11923: validation error text now mentions String, bool, integer, and f64 types to match `is_supported_cli_type`.

File: curvine-common/macros/src/client_cli.rs [hunk 4]
```diff
@@ -0,0 +1,275 @@
...
+}
+
+fn client_cli_attr(field: &Field) -> Option<ClientCliAttr> {
+    for attr in &field.attrs {
+        if attr.path().is_ident("client_cli") {
+            return attr.parse_args().ok();
+        }
+    }
+    None
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs]: Fixed in 6f11923: `client_cli_attr` returns `syn::Result` and duplicate/malformed `#[client_cli]` attributes surface as compile errors.

File: curvine-common/macros/tests/derive_client_cli.rs [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+struct SampleClientConf {
+    #[client_cli(skip)]
+    master_addrs: String,
+
+    #[client_cli(long = "client.io-threads")]
+    io_threads: usize,
+
+    #[serde(alias = "block_size")]
+    block_size_str: String,
+}
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/tests/derive_client_cli.rs:38]: Fixed in 6f11923: integration test adds `Option<String>` with `#[serde(alias = "hugepage", default)]` and a `#[serde(skip)]` field.

File: curvine-common/macros/tests/derive_client_cli.rs [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+        block_size_str: "1MB".to_string(),
+    };
+    let overrides = SampleClientConfCliOverrides {
+        io_threads: Some(8),
+        block_size_str: Some("128MB".to_string()),
+    };
+    overrides.apply_to(&mut conf).unwrap();
+    assert_eq!(conf.io_threads, 8);
+    assert_eq!(conf.block_size_str, "128MB");
+}
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/tests/derive_client_cli.rs:68]: Fixed in 6f11923: test initializes and asserts the optional `hugepage_str` field after `apply_to`.

File: curvine-common/macros/src/client_cli.rs [hunk 7]
```diff
@@ -0,0 +1,275 @@
...
+        return true;
+    }
+    field.attrs.iter().any(|attr| {
+        attr.path().is_ident("client_cli")
+            && attr
+                .parse_args::<ClientCliAttr>()
+                .map(|a| a.skip)
+                .unwrap_or(false)
+    })
+}
```
[the remark this answers is not in the document]
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs]: Fixed in 6f11923: fields marked `#[serde(skip)]` are implicitly skipped by the derive, in addition to `#[client_cli(skip)]` and the `master_addrs` special case.

File: curvine-common/macros/src/client_cli.rs [hunk 8]
```diff
@@ -0,0 +1,326 @@
...
+
+        override_fields.push(quote! {
+            #[arg(long = #long)]
+            pub #ident: #ty,
+        });
+        apply_stmts.push(apply_override_stmt(ident, inner_ty, field_is_option)?);
+    }
+
+    Ok(quote! {
+        #[derive(Debug, Default, Clone, ::clap::Parser, PartialEq, Eq)]
```
Comment (szbr00) [inline curvine-common/macros/src/client_cli.rs]: Two problems with this derive line that will bite C3 the moment it derives on `ClientConf`:

1. **`Eq` is incompatible with `f64` support.** `is_supported_cli_type` (L302+) explicitly allows `f64`, so the override field is `Option<f64>`. But `f64` does not implement `Eq` (NaN-related), so `Option<f64>: !Eq`, and the auto-derive `Eq` here will fail to compile as soon as any target struct has a single `f64` field — which `ClientConf` certainly does for timeouts/factors. The integration test only covers `usize`/`String`/`Option<String>` so this is silent today. Recommend dropping `Eq` (and `PartialEq`, which has no consumer) from the generated derive, or alternatively removing `f64` from `is_supported_cli_type` if comparison is required for some downstream reason.

2. **`::clap::Parser` is the wrong derive for the eventual flatten use-case.** The PR description (and #862's C11 reference) says `ClientCliOverrides` will be flattened into the main `curvine-fuse` / CLI surface via `#[command(flatten)]`. clap's `Parser` is for top-level commands that own `--help`/`--version` and that you call `parse()` on; for embedded argument groups the correct derive is `::clap::Args`. Using `Parser` here means every generated `{Type}CliOverrides` is technically a standalone CLI app, which works in isolation but produces awkward help output and duplicate metadata when flattened. Switching now (before C3 lands) is essentially free.

File: curvine-common/macros/src/client_cli.rs [hunk 9]
```diff
@@ -0,0 +1,326 @@
...
+        }
+    };
+    Ok(assign)
+}
+
+fn should_skip_field(field: &Field) -> syn::Result<bool> {
+    if field
+        .ident
+        .as_ref()
+        .map(|i| i == "master_addrs")
```
Comment (szbr00) [inline curvine-common/macros/src/client_cli.rs]: This file bakes three pieces of `ClientConf`-specific magic into what is presented as a generic `ClientCliArgs` derive:

- L129 hardcodes `master_addrs` as an implicitly-skipped field. Any unrelated struct that happens to have a `master_addrs` field and derives `ClientCliArgs` will get it silently dropped.
- L208 implicitly strips a `_str` suffix from field names (`block_size_str` -> `--client.block-size`). Future fields like `random_str` would silently lose their suffix in the generated flag with no way to opt out.
- L200 hardcodes the `client.` prefix on every flag name, even though the macro is structured to be reusable across configs (a `ClusterConfCliOverrides` would emit `--client.foo-bar` for a non-client field).

Each is a sensible convenience for the current `ClientConf` case, but together they make the macro hard to reuse and surprising to maintain. Two ways to clean up:

1. Require explicit `#[client_cli(skip)]` on `master_addrs` in `ClientConf` itself and remove the hardcoded ident check; document the `_str` suffix and `client.` prefix in the macro doc comment so the conventions are not hidden.
2. Make all three configurable via container-level attributes (e.g. `#[client_cli(prefix = "client", strip_suffix = "_str")]`), so the derive stays generic and the conventions live next to `ClientConf` where they belong.

File: curvine-common/macros/tests/derive_client_cli.rs [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+
+    #[serde(alias = "hugepage", default)]
+    hugepage_str: Option<String>,
+
+    #[serde(skip)]
+    storage_type: String,
+}
+
+#[test]
+fn apply_to_updates_fields() {
```
Comment (szbr00) [inline curvine-common/macros/tests/derive_client_cli.rs:47]: The integration test only exercises the `apply_to` half of the derive — it constructs the override struct by hand and verifies the assignment behavior. The clap-derived parsing half (the whole reason the override struct exists) is never tested: there is no `SampleClientConfCliOverrides::try_parse_from(&["bin", "--client.io-threads", "8", ...])` assertion confirming that flag names, value parsing, and `Option<T>` defaults work end-to-end.

Adding one small `try_parse_from`-based test case would (a) catch the eventual `clap::Parser` vs `clap::Args` migration cleanly, (b) lock in the `client.<kebab>` long-name convention, and (c) verify that `#[client_cli(long = "...")]` overrides actually take effect at parse time, not just at `apply_to`.

File: curvine-common/macros/src/client_cli.rs (hunk 8 above)
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs]: Addressed in e692e65: dropped `PartialEq`/`Eq`, switched generated overrides to `clap::Args` (for flatten), and added an `f64` field to the integration test.

File: curvine-common/macros/src/client_cli.rs (hunk 9 above)
Comment (lzjqsdd) [reply curvine-common/macros/src/client_cli.rs]: Addressed in e692e65 (option 2): removed the hardcoded `master_addrs` skip; added container-level `#[client_cli(prefix = "...", strip_suffix = "...")]` and documented the conventions on the proc-macro. The sample test uses `#[client_cli(prefix = "client", strip_suffix = "_str")]`.

File: curvine-common/macros/tests/derive_client_cli.rs (hunk 10 above)
Comment (lzjqsdd) [reply curvine-common/macros/tests/derive_client_cli.rs:47]: Addressed in e692e65: added `parses_client_cli_flags` using a `CliHarness` wrapper and `try_parse_from` to lock in long-name generation and explicit `#[client_cli(long = ...)]` overrides.

**Comment by lzjqsdd** [comment]
Addressed szbr9486 review in e692e65:
- `clap::Args` instead of `Parser`; drop `Eq`/`PartialEq`
- Container-level `prefix` / `strip_suffix`; remove hardcoded `master_addrs` skip
- Add `try_parse_from` integration test (+ `f64` field)

Rebased on latest `main`.

**Review by szbr00 — APPROVED** [review]

**Review by szbr00 — APPROVED** [review]
